//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyStoreEntities : DbContext
    {
        public MyStoreEntities()
            : base("name=MyStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Order_Items> Order_Items { get; set; }
        public DbSet<Order_Status_Codes> Order_Status_Codes { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Ref_Order_Item_Status_Codes> Ref_Order_Item_Status_Codes { get; set; }
        public DbSet<Ref_Product_Type> Ref_Product_Type { get; set; }
        public DbSet<Unit_Of_Measure> Unit_Of_Measure { get; set; }
    }
}
