//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Status_Codes
    {
        public Order_Status_Codes()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int order_status_id { get; set; }
        public string order_status_description { get; set; }
    
        public virtual ICollection<Order> Orders { get; set; }
    }
}
