//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Items
    {
        public int order_item_id { get; set; }
        public int product_id { get; set; }
        public int order_id { get; set; }
        public int order_item_status_id { get; set; }
        public double order_item_quantity { get; set; }
        public Nullable<decimal> order_item_amount { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Ref_Order_Item_Status_Codes Ref_Order_Item_Status_Codes { get; set; }
        public virtual Product Product { get; set; }
    }
}
