//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStore.App.Models.MyData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ref_Order_Item_Status_Codes
    {
        public Ref_Order_Item_Status_Codes()
        {
            this.Order_Items = new HashSet<Order_Items>();
        }
    
        public int order_item_status_id { get; set; }
        public string order_item_status_description { get; set; }
    
        public virtual ICollection<Order_Items> Order_Items { get; set; }
    }
}
